### ISSUE TITLE
Getting Segmentation fault: 11 on MacOS High Sierra

### ISSUE THREAD

**Issue by ChrisHickeyKenzan** [kenzanlabs/spinikube#26]
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    poll()
  File "setup.py", line 14, in poll
    creating = cmdOut("kubectl get pods --all-namespaces")
  File "setup.py", line 9, in cmdOut
    return subprocess.check_output(cmd, shell=True).strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'kubectl get pods --all-namespaces' returned non-zero exit status -11

**Comment by mcwienczek** [comment]
Works ok for me. Might be your laptop setup. Did you try running `kubectl get pods --all-namespaces` without python wrapper?
